/*
 * Bangla for the studio's own words. Keys are the English sentences.
 *
 * Plain, spoken Bangla with আপনি — the register of bKash or Nagad, not of a
 * government form. Words people already say in English (CV, PDF, template,
 * LinkedIn) stay in English, as they would in conversation. Job titles and
 * example names stay in English because that is how they go on the CV.
 */
export const BN: Record<string, string> = {
  '1. Destination → Save as PDF': '১. Destination থেকে Save as PDF বাছুন',
  '2. Turn off “Headers and footers”, so no web address prints on your CV': '২. “Headers and footers” বন্ধ করুন, যাতে সিভিতে ওয়েব ঠিকানা না ছাপে',
  'A bootcamp or course counts.': 'বুটক্যাম্প বা কোর্সও চলবে।',
  'A letter for this job, written from your CV.': 'এই চাকরির জন্য একটি চিঠি, আপনার সিভি থেকে লেখা।',
  'A little short — aim for 30+ words': 'একটু ছোট — ৩০+ শব্দ লিখুন',
  'A small file with this CV and all its versions': 'এই সিভি আর এর সব ভার্সনসহ ছোট একটি ফাইল',
  'About you': 'আপনার পরিচয়',
  Add: 'যোগ করুন',
  'Add a degree or course': 'ডিগ্রি বা কোর্স যোগ করুন',
  'Add a job': 'চাকরি যোগ করুন',
  'Add a job — or skip if you are new': 'চাকরি যোগ করুন — নতুন হলে বাদ দিন',
  'Add a phone number': 'ফোন নম্বর দিন',
  'Add a photo': 'ছবি দিন',
  'Add a project': 'প্রজেক্ট যোগ করুন',
  'Add a skill': 'দক্ষতা যোগ করুন',
  'Add an email address': 'ইমেইল ঠিকানা দিন',
  'Add at least three skills': 'কমপক্ষে তিনটি দক্ষতা দিন',
  'Add education': 'শিক্ষা যোগ করুন',
  'Add education or training': 'শিক্ষা বা ট্রেনিং যোগ করুন',
  'Add everything once — each role shows the ones that fit.': 'সব একবার যোগ করুন — প্রতিটি পদের সিভিতে মানানসইগুলোই দেখাবে।',
  'Add missing keywords only if they are true': 'যেগুলো নেই, সত্যি হলেই শুধু যোগ করুন',
  'Add the job title you want': 'যে পদে চাকরি চান সেটা লিখুন',
  'Add the job you want': 'কোন চাকরি চান লিখুন',
  'Add your email': 'আপনার ইমেইল দিন',
  'Add your name': 'আপনার নাম দিন',
  Airy: 'খোলামেলা',
  'All sections': 'সব অংশ',
  'Almost there': 'প্রায় হয়ে গেছে',
  'Already in your CV': 'সিভিতে আগেই আছে',
  'Another job': 'আরেকটি চাকরি',
  'Anyone with the link can open and download your {role} CV. The CV travels inside the link — nothing is stored on a server.':
    'লিংক যার কাছে থাকবে, সে আপনার {role} সিভি খুলে ডাউনলোড করতে পারবে। সিভিটা লিংকের ভেতরেই থাকে — কোনো সার্ভারে রাখা হয় না।',
  'Applying for different jobs? Add one — your skills and projects re-pick themselves for it.':
    'ভিন্ন ভিন্ন চাকরিতে আবেদন করছেন? আরেকটি যোগ করুন — দক্ষতা আর প্রজেক্ট নিজে থেকেই বাছাই হবে।',
  'Back to all sections': 'সব অংশে ফিরে যান',
  'Back to portfolio': 'পোর্টফোলিওতে ফিরে যান',
  'Backup downloaded': 'ব্যাকআপ ডাউনলোড হয়েছে',
  'Backup restored': 'ব্যাকআপ থেকে ফিরিয়ে আনা হয়েছে',
  'Banner header': 'ব্যানার হেডার',
  'Build your CV': 'আপনার সিভি বানান',
  'Built with': 'যা দিয়ে বানানো',
  'CV for another job': 'আরেক চাকরির সিভি',
  'CV for which job?': 'কোন চাকরির সিভি?',
  'CV text': 'সিভির লেখা',
  Cancel: 'বাতিল',
  Change: 'বদলান',
  'Change it and your skills and projects re-pick themselves for the new role. Nothing is deleted.':
    'এটা বদলালে নতুন পদের জন্য দক্ষতা আর প্রজেক্ট নিজে থেকেই বাছাই হবে। কিছুই মুছে যাবে না।',
  'Change photo': 'ছবি বদলান',
  'Check this CV against a real job advert.': 'আসল চাকরির বিজ্ঞাপনের সাথে সিভিটা মিলিয়ে দেখুন।',
  'Choose a PDF': 'PDF বাছুন',
  'Choose photo': 'ছবি বাছুন',
  'Choose your CV as a PDF, or your LinkedIn profile saved as PDF (LinkedIn → More → Save to PDF). We fill in what we can — you check the rest.':
    'আপনার সিভির PDF বাছুন, বা LinkedIn প্রোফাইল PDF করে নিন (LinkedIn → More → Save to PDF)। যতটা পারি আমরা পূরণ করব — বাকিটা আপনি দেখে নেবেন।',
  City: 'শহর',
  Classic: 'ক্লাসিক',
  'Clean, two columns': 'পরিচ্ছন্ন, দুই কলাম',
  'Clear it': 'মুছে ফেলুন',
  'Clear this CV and begin again': 'এই সিভি মুছে নতুন করে শুরু করুন',
  Close: 'বন্ধ করুন',
  Colour: 'রং',
  'Colour {c}': 'রং {c}',
  Compact: 'ঘন',
  'Compact helps fit one page': 'ঘন রাখলে এক পাতায় আঁটে',
  Company: 'প্রতিষ্ঠান',
  'Company name': 'প্রতিষ্ঠানের নাম',
  Contact: 'যোগাযোগ',
  Copy: 'কপি',
  'Copy link': 'লিংক কপি',
  'Copy text': 'লেখা কপি',
  'Could not copy the link': 'লিংক কপি করা গেল না',
  'Could not copy — select the text and copy it': 'কপি হলো না — লেখাটা সিলেক্ট করে কপি করুন',
  'Cover letter': 'কভার লেটার',
  'Create CV': 'সিভি বানান',
  'Create CV for {role}': '{role}-এর সিভি বানান',
  'Dark header': 'গাঢ় হেডার',
  'Dark left panel': 'বামে গাঢ় প্যানেল',
  'Dark sidebar': 'গাঢ় সাইডবার',
  'Dated timeline': 'তারিখসহ টাইমলাইন',
  Dates: 'সময়কাল',
  'Degrees, diplomas, bootcamps and courses.': 'ডিগ্রি, ডিপ্লোমা, বুটক্যাম্প আর কোর্স।',
  Delete: 'মুছুন',
  'Delete the {role} CV?': '{role} সিভিটা মুছবেন?',
  'Delete {name}': '{name} মুছুন',
  'Delete {name}?': '{name} মুছবেন?',
  'Describe a job in more than one line': 'একটি চাকরির বর্ণনা একাধিক লাইনে লিখুন',
  Design: 'ডিজাইন',
  'Developer style': 'ডেভেলপার স্টাইল',
  'Doesn’t mention {role} yet': 'এখনো {role}-এর কথা নেই',
  Done: 'হয়ে গেছে',
  Download: 'ডাউনলোড',
  'Download PDF': 'PDF ডাউনলোড',
  'Download anyway': 'তবুও ডাউনলোড',
  'Download backup': 'ব্যাকআপ ডাউনলোড',
  'Download letter': 'চিঠি ডাউনলোড',
  'Draft written — read it through and make it yours': 'খসড়া তৈরি — একবার পড়ে নিজের মতো করে নিন',
  'Each CV version keeps its own letter. This one is for {role}.': 'প্রতিটি সিভি ভার্সনের নিজের চিঠি থাকে। এটা {role}-এর জন্য।',
  Edit: 'এডিট',
  'Edited your CV later? Share a new link — an old link keeps the old version.': 'পরে সিভি বদলালে নতুন লিংক শেয়ার করুন — পুরনো লিংকে পুরনো সিভিই থাকবে।',
  Education: 'শিক্ষা',
  Email: 'ইমেইল',
  'Fill it in once. Pick the job you want, and your CV picks the right skills and projects for it. Free, no sign-up.':
    'একবার তথ্য দিন। যে চাকরি চান সেটা বাছুন, সিভি নিজেই মানানসই দক্ষতা আর প্রজেক্ট বেছে নেবে। ফ্রি, সাইন-আপ লাগবে না।',
  'Fix first': 'আগে ঠিক করি',
  Font: 'ফন্ট',
  Formal: 'আনুষ্ঠানিক',
  Found: 'পাওয়া গেছে',
  Friendly: 'আন্তরিক',
  'From a PDF or your LinkedIn profile': 'PDF বা LinkedIn প্রোফাইল থেকে',
  'Full name': 'পুরো নাম',
  'Here is what we found': 'যা পাওয়া গেল',
  'Hi {name} 👋': 'হ্যালো {name} 👋',
  'Hidden in the {role} CV': '{role} সিভিতে লুকানো',
  'Hidden — tap to show': 'লুকানো — দেখাতে ট্যাপ করুন',
  Hide: 'লুকান',
  'Hiring manager': 'হায়ারিং ম্যানেজার',
  'How recruiters reach you. Email matters most.': 'রিক্রুটার কীভাবে যোগাযোগ করবে। ইমেইল সবচেয়ে জরুরি।',
  'I work here now': 'এখন এখানে কাজ করছি',
  'Import my old CV': 'পুরনো সিভি থেকে আনুন',
  'Import your old CV': 'পুরনো সিভি আনুন',
  'Imported — check each section': 'আনা হয়েছে — প্রতিটি অংশ একবার দেখে নিন',
  'In the print window that opens:': 'যে প্রিন্ট উইন্ডো খুলবে সেখানে:',
  'In this CV — tap to hide': 'এই সিভিতে আছে — লুকাতে ট্যাপ করুন',
  'Include my photo': 'আমার ছবি রাখুন',
  'It is a draft — check each section after, especially job titles and dates.': 'এটা খসড়া — পরে প্রতিটি অংশ দেখে নিন, বিশেষ করে পদবি আর তারিখ।',
  'It is the first thing a recruiter looks for.': 'রিক্রুটার সবার আগে এটাই খোঁজেন।',
  'It will be removed from every version of your CV.': 'আপনার সিভির সব ভার্সন থেকেই এটা মুছে যাবে।',
  'Job advert': 'চাকরির বিজ্ঞাপন',
  'Job match': 'জব ম্যাচ',
  'Job title': 'পদবি',
  'Job title in the advert': 'বিজ্ঞাপনে দেওয়া পদবি',
  'Job you want': 'যে চাকরি চান',
  Jobs: 'চাকরি',
  'Keep it safe': 'নিরাপদ রাখুন',
  Language: 'ভাষা',
  'Letter copied': 'চিঠি কপি হয়েছে',
  Link: 'লিংক',
  'Link copied — paste it anywhere': 'লিংক কপি হয়েছে — যেকোনো জায়গায় পেস্ট করুন',
  'Live preview': 'লাইভ প্রিভিউ',
  'Make a CV that fits the job': 'চাকরির সাথে মানানসই সিভি বানান',
  'Make a CV version for this job': 'এই চাকরির জন্য সিভি ভার্সন বানান',
  'Makes the link longer': 'লিংক একটু লম্বা হবে',
  'Making your link…': 'লিংক তৈরি হচ্ছে…',
  Manage: 'ম্যানেজ',
  Match: 'ম্যাচ',
  'Match it to the role you are applying for, not the one you have.': 'যে পদে আবেদন করছেন সেটা লিখুন, এখনকারটা নয়।',
  'Minimal, typographic': 'মিনিমাল, টাইপোগ্রাফিক',
  'Missing — add the ones that are true': 'নেই — সত্যি হলে যোগ করুন',
  Modern: 'মডার্ন',
  'More tools': 'আরও টুল',
  'More: your CVs, backup, start over': 'আরও: আপনার সিভি, ব্যাকআপ, নতুন করে শুরু',
  'Most of a CV is what you did and what changed because of it.': 'সিভির বেশিরভাগই হলো আপনি কী করেছেন আর তাতে কী বদলেছে।',
  'Most recent first. Freelance, part-time and internships count.': 'সবচেয়ে নতুনটা আগে। ফ্রিল্যান্স, পার্ট-টাইম আর ইন্টার্নশিপও চলবে।',
  'Move down': 'নিচে সরান',
  'Move up': 'উপরে সরান',
  'My CV': 'আমার সিভি',
  Name: 'নাম',
  'New CV': 'নতুন সিভি',
  'New CV for {role}: {s} skills, {p} projects picked': '{role}-এর নতুন সিভি: {s}টি দক্ষতা, {p}টি প্রজেক্ট বাছাই হয়েছে',
  'Next: {name}': 'পরের ধাপ: {name}',
  'No work experience yet? That is fine — projects and education can carry a first CV.':
    'এখনো চাকরির অভিজ্ঞতা নেই? সমস্যা নেই — প্রথম সিভিতে প্রজেক্ট আর শিক্ষাই যথেষ্ট।',
  Normal: 'স্বাভাবিক',
  'One CV, a version for each job. Your jobs and skills are shared — each version shows the ones that fit its role. To rename one, change “Job you want” in About you.':
    'একটাই সিভি, প্রতিটি চাকরির জন্য আলাদা ভার্সন। চাকরি আর দক্ষতা সব ভার্সনে একই — প্রতিটি ভার্সন নিজের পদের সাথে মানানসইগুলো দেখায়। নাম বদলাতে “আপনার পরিচয়” থেকে “যে চাকরি চান” বদলান।',
  'One CV, every job': 'এক সিভি, সব চাকরি',
  'One colour stripe': 'এক রঙের স্ট্রাইপ',
  'One line about it': 'এক লাইনে পরিচয়',
  'One line per role reads as a job list. Say what you built and what it changed.': 'প্রতি চাকরিতে এক লাইন লিখলে শুধু তালিকার মতো লাগে। কী বানিয়েছেন আর তাতে কী বদলেছে লিখুন।',
  'Only the {role} version uses this text. Name the tools you want to be hired for — screening software reads this first.':
    'এই লেখা শুধু {role} ভার্সনে থাকবে। যেসব টুলের জন্য চাকরি চান সেগুলোর নাম লিখুন — স্ক্রিনিং সফটওয়্যার এটাই আগে পড়ে।',
  'Only this version goes. Your jobs, skills and projects stay in the others.': 'শুধু এই ভার্সনটা মুছবে। চাকরি, দক্ষতা আর প্রজেক্ট বাকিগুলোতে থেকে যাবে।',
  'Only {n} shown — add a few more': 'মাত্র {n}টি দেখাচ্ছে — আরও কয়েকটি দিন',
  'Open a backup file made here': 'এখানে বানানো ব্যাকআপ ফাইল খুলুন',
  'Open full preview': 'পুরো প্রিভিউ খুলুন',
  'Open link': 'লিংক খুলুন',
  'Open preview': 'প্রিভিউ খুলুন',
  'Opened an example CV': 'একটি উদাহরণ সিভি খোলা হয়েছে',
  'Optional — one project helps you stand out': 'ঐচ্ছিক — একটি প্রজেক্ট থাকলে আলাদা করে চোখে পড়ে',
  'Optional. Many recruiters prefer CVs without one.': 'ঐচ্ছিক। অনেক রিক্রুটার ছবি ছাড়া সিভি পছন্দ করেন।',
  'Partial match': 'আংশিক মিল',
  'Paste a bit more of the advert to check it.': 'যাচাই করতে বিজ্ঞাপনের আরও কিছু অংশ পেস্ট করুন।',
  'Paste a job advert. We show which of its keywords your CV already covers — counted honestly, from your own words only.':
    'চাকরির বিজ্ঞাপন পেস্ট করুন। এর কোন কিওয়ার্ডগুলো আপনার সিভিতে আছে দেখাব — শুধু আপনার নিজের লেখা থেকে, সৎভাবে গুনে।',
  'Paste the job advert, so the letter mentions what it asks for': 'চাকরির বিজ্ঞাপন পেস্ট করুন, যাতে চিঠিতে তাদের চাহিদার কথা থাকে',
  'Paste the job description here…': 'চাকরির বিবরণ এখানে পেস্ট করুন…',
  'Paste the whole advert, not just the title': 'শুধু পদবি নয়, পুরো বিজ্ঞাপনটা পেস্ট করুন',
  'Paste your CV or LinkedIn profile text here…': 'আপনার সিভি বা LinkedIn প্রোফাইলের লেখা এখানে পেস্ট করুন…',
  Phone: 'ফোন',
  Photo: 'ছবি',
  'Photo added': 'ছবি যোগ হয়েছে',
  'Photo sidebar': 'ছবিসহ সাইডবার',
  'Pick a job': 'চাকরি বাছুন',
  'Pick a job. We choose the skills and projects that fit it and put the strongest first — you can change anything after.':
    'একটি চাকরি বাছুন। আমরা মানানসই দক্ষতা আর প্রজেক্ট বেছে সবচেয়ে ভালোগুলো আগে রাখব — পরে যেকোনো কিছু বদলাতে পারবেন।',
  'Pick the job you want': 'কোন চাকরি চান বাছুন',
  'Pinch to zoom. A dashed line marks where a new page starts.': 'বড় করে দেখতে দুই আঙুলে টানুন। ড্যাশ দাগ মানে নতুন পাতা শুরু।',
  'Popular for {role}': '{role}-এর জন্য জনপ্রিয়',
  Preview: 'প্রিভিউ',
  'Professional summary': 'পেশাগত সারাংশ',
  'Project name': 'প্রজেক্টের নাম',
  Projects: 'প্রজেক্ট',
  'Proof beats claims, especially early in a career.': 'দাবির চেয়ে প্রমাণ বেশি কাজের, বিশেষ করে ক্যারিয়ারের শুরুতে।',
  Qualification: 'যোগ্যতা',
  'Re-picked for {role}: {s} skills, {p} projects': '{role}-এর জন্য আবার বাছাই: {s}টি দক্ষতা, {p}টি প্রজেক্ট',
  'Read my CV': 'আমার সিভি পড়ুন',
  'Read on this device. Nothing is uploaded.': 'এই ডিভাইসেই পড়া হয়। কিছুই আপলোড হয় না।',
  'Reading your file…': 'ফাইল পড়া হচ্ছে…',
  'Ready in minutes': 'কয়েক মিনিটে তৈরি',
  'Ready to send': 'পাঠানোর জন্য তৈরি',
  'Recruiters often call before they email.': 'রিক্রুটাররা প্রায়ই ইমেইলের আগে ফোন করেন।',
  Remove: 'সরান',
  'Removed {name}': '{name} সরানো হয়েছে',
  Replace: 'বদলে দিন',
  'Replace your letter?': 'চিঠিটা বদলে দেবেন?',
  'Replace your summary?': 'সারাংশটা বদলে দেবেন?',
  'Reset colour, font and spacing': 'রং, ফন্ট আর স্পেসিং আগের মতো করুন',
  'Restore a backup': 'ব্যাকআপ থেকে আনুন',
  'Restore backup': 'ব্যাকআপ ফিরিয়ে আনুন',
  Round: 'গোল',
  'Safest for job portals': 'জব পোর্টালের জন্য সবচেয়ে নিরাপদ',
  'Saved on this device': 'এই ডিভাইসে সেভ আছে',
  'Say what you built and what changed because of it — a number, a time saved, a problem fixed.':
    'কী বানিয়েছেন আর তাতে কী বদলেছে লিখুন — কোনো সংখ্যা, বাঁচানো সময়, বা সমাধান করা সমস্যা।',
  'School or institute': 'স্কুল বা প্রতিষ্ঠান',
  'Screening software matches these against the posting.': 'স্ক্রিনিং সফটওয়্যার এগুলো বিজ্ঞাপনের সাথে মেলায়।',
  Sections: 'অংশসমূহ',
  'See an example': 'উদাহরণ দেখুন',
  'See example': 'উদাহরণ দেখুন',
  'Send your CV on WhatsApp, Messenger or email': 'WhatsApp, Messenger বা ইমেইলে সিভি পাঠান',
  'Serif, centred': 'সেরিফ, মাঝখানে',
  Share: 'শেয়ার',
  'Share as a link': 'লিংক হিসেবে শেয়ার',
  'Share your CV as a link': 'সিভি লিংক হিসেবে শেয়ার করুন',
  'Share…': 'শেয়ার…',
  'Show in the {role} CV': '{role} সিভিতে দেখান',
  'Show in this CV': 'এই সিভিতে দেখান',
  'Showing your {role} CV': 'আপনার {role} সিভি দেখানো হচ্ছে',
  Skills: 'দক্ষতা',
  Spacing: 'স্পেসিং',
  Square: 'চারকোনা',
  'Start a line with': 'লাইন শুরু করুন',
  'Start my CV': 'সিভি বানানো শুরু করুন',
  'Start over': 'নতুন করে শুরু',
  'Start over?': 'নতুন করে শুরু করবেন?',
  'Started a fresh CV': 'নতুন সিভি শুরু হয়েছে',
  'Stays on your device': 'আপনার ডিভাইসেই থাকে',
  'Strong match': 'ভালো মিল',
  Studio: 'স্টুডিও',
  Summary: 'সারাংশ',
  'Tap a style — your CV changes instantly.': 'একটি স্টাইল ট্যাপ করুন — সিভি সাথে সাথে বদলাবে।',
  'Tap one to edit': 'এডিট করতে ট্যাপ করুন',
  'Tap to add details': 'তথ্য দিতে ট্যাপ করুন',
  'Tap “Write my letter” for a draft, or write your own here.': 'খসড়ার জন্য “চিঠি লিখে দিন” ট্যাপ করুন, বা এখানে নিজেই লিখুন।',
  Template: 'টেমপ্লেট',
  'That file could not be read. If it is a scanned PDF (a photo of a CV), copy the text and paste it instead.':
    'ফাইলটা পড়া গেল না। স্ক্যান করা PDF (সিভির ছবি) হলে লেখাটা কপি করে পেস্ট করুন।',
  'That image could not be read. Try a JPG or PNG.': 'ছবিটা পড়া গেল না। JPG বা PNG দিয়ে চেষ্টা করুন।',
  'The switch shows or hides an item in your {role} CV only. Your other versions keep their own choice.':
    'সুইচ দিয়ে শুধু {role} সিভিতে দেখানো বা লুকানো হয়। অন্য ভার্সনগুলো নিজের মতো থাকে।',
  'Then make a version for that job in one tap': 'তারপর এক ট্যাপে ওই চাকরির ভার্সন বানান',
  'This clears everything in this CV. It cannot be undone — download a backup first if you might want it.':
    'এতে এই সিভির সবকিছু মুছে যাবে, আর ফেরত আনা যাবে না — দরকার হতে পারে মনে হলে আগে ব্যাকআপ নিন।',
  'This link is long. Some apps cut long links — try it without the photo.': 'লিংকটা লম্বা। কিছু অ্যাপ লম্বা লিংক কেটে দেয় — ছবি ছাড়া চেষ্টা করুন।',
  'This summary doesn’t mention anything a {role} would. Rewrite it, or tap “Write a draft for me”.':
    'এই সারাংশে {role} সম্পর্কিত কিছু নেই। নতুন করে লিখুন, বা “খসড়া লিখে দিন” ট্যাপ করুন।',
  'Three or four lines: who you are, what you build, what you are after.': 'তিন-চার লাইন: আপনি কে, কী করেন, কী চান।',
  Tone: 'লেখার ধরন',
  'Try again': 'আবার চেষ্টা',
  'Two or three lines at the top — each role gets its own.': 'উপরে দুই-তিন লাইন — প্রতিটি পদের জন্য আলাদা।',
  'Type a skill, e.g. Figma': 'দক্ষতা লিখুন, যেমন Figma',
  'Untitled job': 'নামহীন চাকরি',
  'Untitled project': 'নামহীন প্রজেক্ট',
  'Untitled qualification': 'নামহীন যোগ্যতা',
  'Use this': 'এটাই নিন',
  'We could not find CV sections in that text. Check it is your CV, or type it in instead.':
    'লেখাটায় সিভির অংশ খুঁজে পাওয়া গেল না। এটা আপনার সিভি কিনা দেখুন, অথবা নিজে লিখে দিন।',
  'We will write a new draft from your CV. Your current text will be replaced.': 'আপনার সিভি থেকে নতুন খসড়া লেখা হবে। এখনকার লেখা বদলে যাবে।',
  'We will write a starter from your jobs and skills. You can edit it after.': 'আপনার চাকরি আর দক্ষতা থেকে একটা শুরু লিখে দেব। পরে এডিট করতে পারবেন।',
  'Weak match': 'কম মিল',
  'Website or portfolio': 'ওয়েবসাইট বা পোর্টফোলিও',
  'Welcome 👋': 'স্বাগতম 👋',
  'What it is and who it is for': 'কী এটা, কাদের জন্য',
  'What you did': 'কী কাজ করেছেন',
  'Without it nobody can reply to you.': 'এটা ছাড়া কেউ আপনাকে উত্তর দিতে পারবে না।',
  'Work experience': 'কাজের অভিজ্ঞতা',
  'Work that proves your skills. Great early in a career.': 'যে কাজ আপনার দক্ষতা প্রমাণ করে। ক্যারিয়ারের শুরুতে খুব কাজের।',
  'Write a draft for me': 'খসড়া লিখে দিন',
  'Write a new draft': 'নতুন খসড়া লিখুন',
  'Write a short summary': 'ছোট একটা সারাংশ লিখুন',
  'Write my letter': 'চিঠি লিখে দিন',
  'Write one for {role} in a minute': 'এক মিনিটে {role}-এর জন্য লিখুন',
  'Write two or three lines': 'দুই-তিন লাইন লিখুন',
  'Write your letter first': 'আগে চিঠিটা লিখুন',
  Written: 'লেখা হয়েছে',
  'Written for {name}': '{name}-এর জন্য লেখা',
  'Written for {role}': '{role}-এর জন্য লেখা',
  Yes: 'হ্যাঁ',
  'You already have a CV for {role}.': '{role}-এর সিভি আগেই আছে।',
  'Your CV is ready': 'আপনার সিভি তৈরি',
  'Your CV is saved in this browser only — nothing is uploaded. A backup file moves it to another phone or computer.':
    'আপনার সিভি শুধু এই ব্রাউজারে সেভ থাকে — কিছুই আপলোড হয় না। অন্য ফোন বা কম্পিউটারে নিতে ব্যাকআপ ফাইল ব্যবহার করুন।',
  'Your CV or LinkedIn profile': 'আপনার সিভি বা LinkedIn প্রোফাইল',
  'Your CV versions': 'আপনার সিভি ভার্সন',
  'Your CVs': 'আপনার সিভি',
  'Your letter': 'আপনার চিঠি',
  'Your name': 'আপনার নাম',
  'Your name, photo and the job you want.': 'আপনার নাম, ছবি আর যে চাকরি চান।',
  'Your photo': 'আপনার ছবি',
  'Your skills': 'আপনার দক্ষতা',
  'Your {role} CV has everything recruiters look for. Download it as a PDF job portals can read.':
    'আপনার {role} সিভিতে রিক্রুটারের দরকারি সবকিছু আছে। জব পোর্টাল পড়তে পারে এমন PDF হিসেবে ডাউনলোড করুন।',
  'comma separated': 'কমা দিয়ে আলাদা',
  current: 'বর্তমান',
  'e.g. Ayesha Rahman': 'যেমন: Ayesha Rahman',
  'e.g. Brain Station 23': 'যেমন: Brain Station 23',
  'e.g. Ms. Nusrat Jahan': 'যেমন: Ms. Nusrat Jahan',
  'no company yet': 'প্রতিষ্ঠান দেওয়া হয়নি',
  'not found': 'পাওয়া যায়নি',
  'one point per line': 'প্রতি লাইনে একটি পয়েন্ট',
  optional: 'ঐচ্ছিক',
  'or paste the text': 'অথবা লেখা পেস্ট করুন',
  'shapes the whole CV': 'পুরো সিভি এর উপর নির্ভর করে',
  'this entry': 'এই এন্ট্রি',
  'this job': 'এই চাকরি',
  'this project': 'এই প্রজেক্ট',
  'this role': 'এই পদ',
  untitled: 'নামহীন',
  '{m} of {k} keywords from the advert are in this CV.': 'বিজ্ঞাপনের {k}টি কিওয়ার্ডের মধ্যে {m}টি এই সিভিতে আছে।',
  '{name}’s CV': '{name}-এর সিভি',
  '{n} entries': '{n}টি এন্ট্রি',
  '{n} entry': '{n}টি এন্ট্রি',
  '{n} job': '{n}টি চাকরি',
  '{n} jobs': '{n}টি চাকরি',
  '{n} shown': '{n}টি দেখাচ্ছে',
  '{n} thing recruiters look for is still empty.': 'রিক্রুটারের দরকারি {n}টি জিনিস এখনো খালি।',
  '{n} things recruiters look for are still empty.': 'রিক্রুটারের দরকারি {n}টি জিনিস এখনো খালি।',
  '{n} words': '{n} শব্দ',
  '{n} words — good length.': '{n} শব্দ — ঠিকঠাক দৈর্ঘ্য।',
  '{n} words. Keep the 3–4 strongest points so it stays easy to scan.': '{n} শব্দ। সবচেয়ে ভালো ৩–৪টি পয়েন্ট রাখুন, যাতে চোখ বুলিয়েই পড়া যায়।',
  '{n} words. One more concrete point would help.': '{n} শব্দ। আরও একটা নির্দিষ্ট পয়েন্ট দিলে ভালো হয়।',
  '{n}% ready': '{n}% তৈরি',
  '{shown} of {n} in this CV · tap to show or hide': '{n}টির মধ্যে {shown}টি এই সিভিতে · দেখাতে বা লুকাতে ট্যাপ করুন',
  '{shown} of {n} shown': '{n}টির মধ্যে {shown}টি দেখাচ্ছে',
  '{shown} of {n} shown for {role}': '{role}-এর জন্য {n}টির মধ্যে {shown}টি',
  '· a bit short': '· একটু ছোট',
  '· good length': '· ঠিকঠাক',
  '· keep it under one page': '· এক পাতার মধ্যে রাখুন',
  '· trim it down': '· একটু ছোট করুন',
}
